### ISSUE TITLE
⬆️ Upgrade to latest everything 🎉 

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#680]
At long last, after clearing the decks with
https://github.com/e-mission/e-mission-phone/pull/799
https://github.com/e-mission/e-mission-phone/pull/800
https://github.com/e-mission/e-mission-phone/pull/801
https://github.com/e-mission/e-mission-phone/pull/802

I'm ready to start the annual ritual of upgrading to the most recent version of everything.
I will also plan to address https://github.com/e-mission/e-mission-docs/issues/678
and add silent push notifications to android as well to address https://github.com/e-mission/e-mission-docs/issues/677

**Comment by shankari** [comment]
Switched to cordova android@10.1.0, which is the most recent version (https://cordova.apache.org/announcements/2021/08/16/cordova-android-10.1.0.html).

It generated a warning about the targetSDK version being 30+, which is also required for any updates to the play store.

Looking at the behavior changes between android 10 (API 29) and android 11 (API 30), we have:
https://developer.android.com/about/versions/11/behavior-changes-all

- **One-time permissions**: Gives users the option to grant more temporary access to location, microphone, and camera permissions.
   - not significant, just another failure case which we need to handle
- **Permission dialog visibility**: Repeated denials of a permission implies "don't ask again."
   - not significant, we already have to open the app settings to get our "Always" permission anyway
- **Auto-reset permissions from unused apps**
   - this is new and annoying. Details at https://developer.android.com/topic/performance/app-hibernation. At first glance, seems to be similar to the "Always" re-check and prompt on iOS
- **Background location access**:
   - need to request foreground and background separately: not an issue since we don't actually request foreground access
   - "Allow all the time" not visible in system dialog; need to go to the app settings screen to fix.

**Comment by shankari** [comment]
ok, so the hibernation changes are pretty evil and are going to get more evil in android 12 (API 31). In API 31, if the app is not launched (in the foreground) "for a few months", the app hibernates.

In API 30, the app runtime permissions (including location) are reset.
In API 31:
- the app runtime permissions are reset
- the app cannot run jobs or alerts from the background,
- the app cannot receive push notifications
- files in the app cache (including the DB?) are removed.

This is pretty darn terrible. The location permission will be reset, and we won't have the ability to notify the user that anything is wrong through notifications.

Apparently, if your app is primarily targets with background operation, you can ask users to exempt the app from hibernation. We are going to have to go down this route; fortunately, there is a programmatic way to do this.
https://developer.android.com/topic/performance/app-hibernation#exemption

Maybe we should just upgrade to API 31 right now and be a bit more future-proof. Let's see what other changes API 31 needs.

**Comment by shankari** [comment]
Note also that we can't put this off forever because, in Dec 2021, this reset permission is going to come to devices that: "Runs Android 6.0 (API level 23) to Android 10 (API level 29), inclusive, and is powered by Google Play services" as long as the targetSDK is 11. And we need targetSDK 11 for any native code updates.

So we may be able to limp along for a bit but will have to deal with it fully sometime.

**Comment by shankari** [comment]
The foreground service launch restrictions are the worst. Basically, we can't restart the foreground service except for exemptions. Most of those don't apply.

- The most relevant option is: Your app receives an event that's related to geofencing or activity recognition transition. We should then be able to start the app when we do need the fine grained location access. But what happens if the service is killed while we are on the trip? That is not a geofence transition, and we are in the background. Or do they argue that this never happens.

- There is also an option to turn off battery optimizations for the app. We may have to fallback to that if the foreground service can indeed be killed during a trip (and I don't see any guarantees that it won't be).

**Comment by shankari** [comment]
Whitelist is deprecated in cordova android 10.x and greater (https://github.com/apache/cordova-plugin-whitelist). However, removing it requires updating the ionic plugin.

```
$ npx cordova plugin rm cordova-plugin-whitelist
The plugin 'cordova-plugin-whitelist' is required by (cordova-plugin-ionic), skipping uninstallation. (try --force if trying to update)
```

**Comment by shankari** [comment]
We are currently at `cordova-plugin-ionic 5.4.7`, currently latest is `5.5.1`, so hopefully we won't have too much of an interface change. And the whitelist dependency was removed in https://github.com/ionic-team/cordova-plugin-ionic/commit/34a202e0c444d11b54664c7918219d88e8dfac6c#diff-6813833f33103dfcaa583d4f09e06dc84c0ce8ddd34c8b567b56c9728be58389 in v5.5.0, so upgrading to v5.5.1 should be good enough.

Builds now!!

```
BUILD SUCCESSFUL in 11s
49 actionable tasks: 18 executed, 31 up-to-date
Built the following apk(s):
	/Users/kshankar/e-mission/e-mission-phone/platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

**Comment by shankari** [comment]
Note other android 10 updates (https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html), notably:
- migration away from `file://` URLs (which we should not be using anyway). Does this mean that we don't need a custom webview and/or the http adapter plugin?
- update plugins to androidx. we should probably:
  - update our plugins to androidx
  - update other plugins to the most recent version
  - we do still have the androidx adapter in case the other plugins have not been adapted
- the release generates an aab instead of an apk by default, consistent with the new packaging requirements
  (https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html). We will need to upgrade our packaging scripts.

**Comment by shankari** [comment]
wrt file:// plugins, we use them only in the context of the post-trip prompt.

```
www//js/incident/post-trip-prompt.js|51| icon: 'file://img/icon.png',
www//js/survey/multilabel/post-trip-prompt.js|54| icon: 'file://img/icon.png',
www//js/control/general-settings.js|242| icon: 'file://img/icon.png',
```

so we need to see how the local notifications work with it.
If this is too complex, I may drop support for the trip end notifications plugin.

**Comment by shankari** [comment]
Android Studio cannot open the project, though.
"Gradle sync failed: This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer."

Trying to figure out how to upgrade the android support plugin. Might just upgrade to a newer version of Android studio if it is easier.

**Comment by shankari** [comment]
Looks like we can fix it either by downgrading gradle or upgrading android studio.
Since a major upgrade to gradle 7.1.1 was part of the cordova 10 upgrade, we will upgrade android studio.

**Comment by shankari** [comment]
upgraded to latest version of cocoapods using the standard install command without a version

```
gem install --no-document --user-install cocoapods -v $COCOAPODS_VERSION
```

and then upgrading the version to the selected 1.11.2

**Comment by shankari** [comment]
Android is a bit trickier because we need to change our upload process to support the aab bundles. It looks like apk is also available for older apps, so we could use that workaround for now, but what better time to make the inevitable change than during a formal upgrade process.

**Comment by shankari** [comment]
Phew! https://github.com/e-mission/e-mission-docs/issues/680#issuecomment-946975792 is just because the emulators didn't have Google Play Services installed. Should improve the error reporting around this because "unknown error" is not very useful and won't help people figure out what is wrong.

**Comment by shankari** [comment]
Got error while signing aab:

```
The signer's certificate is self-signed.
The RSA signing key has a keysize of 1024 which is considered a security risk. This key size will be disabled in a future update.
```

Should I have used a new signing key? How would that have even worked? I thought you had to export your signing key to start. Anyway, you can reset your key once, and this app is only valid for 2 more years, so it's probably OK.

**Comment by shankari** [comment]
Suspension does seem to be related to Google Play store suspension. I cannot find any other examples of it, and the the API signature `PackageManager#setPackagesSuspended(String[], boolean, PersistableBundle, PersistableBundle, setPackagesSuspended)` seems to indicate that the user has other ways of knowing that the app has been suspended.

Finding the appropriate method in the Android Open Source codebase:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/pm/PackageManager.java#7912

```
     * Puts the package in a suspended state, where attempts at starting activities are denied.
     * When the user tries to launch a suspended app, a system dialog with the given dialogMessage
```

It does not look like the user can fix this. The user can't even launch the activity to fix this.

The distracting packages are different.

```
* These packages can have certain restrictions set that should discourage the user to launch
them often. For example, notifications from such an app can be hidden, or the app can be removed from launcher suggestions, so the user is able to restrict their use of these apps.
```

Again, it is not clear how the user can clear these restrictions.

Ah I found it by searching the settings.

<img width="360px" src="https://user-images.githubusercontent.com/2423263/139482917-63542a9f-7d57-400d-b5bd-a5a946f5e395.png"/>

**Comment by shankari** [comment]
There does not seem to be a way to open that screen - there is no settings constant for now.
https://developer.android.com/reference/android/provider/Settings

I think we should ignore the notification paused checks for now.
- if the package is suspended, the user can't launch the app any more and will surely notice
- if the package is marked as distracting, and won't show notifications during focus times, that is not too bad. We want to honor user attention spans and allow them to engage with the app on their terms. And presumably the notifications will show up at non-focus times. I will test this on my android 11 phone, but getting feedback from other beta testers would also be great.

Given all this, I don't think we should add a section on "notifications paused" to the status screen. I am going to commit the change and then roll back the UI only changes. This allows us to re-enable the check with UI-only changes later if we need to.

**Comment by shankari** [comment]
Also storing the UI change as a patch here in case we need it later.
[paused_notification_check_support.patch.gz](https://github.com/e-mission/e-mission-docs/files/7444331/paused_notification_check_support.patch.gz)

**Comment by shankari** [comment]
Moving on to the background restrictions, we start with the auto-reset of permissions for rarely used apps
(https://github.com/e-mission/e-mission-docs/issues/680#issuecomment-945047105).

There is a workaround which involves compat libraries from androidx (https://developer.android.com/topic/performance/app-hibernation#handle-hibernation-android10-lower).

However, the API is in the most recent version of androidX, which has a minCompileSDK of 31. cordova supports 30 by default, and doesn't have a way to override without also overridding the **target** SDK.

Filed https://github.com/apache/cordova-android/issues/1373

Trying to manually override to API 31 and see if it works.

**Comment by shankari** [comment]
Did not work, got error 


```
> Task :app:compileDebugJavaWithJavac FAILED
An exception has occurred in the compiler (1.8.0_252). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
```

Downgraded to API 30, confirmed that it worked.

Removed all SDK, just in case that was the issue.

Re-ran with API 30.

Got logs

```
Checking the license for package Android SDK Platform 30 in /Users/kshankar/Library/Android/sdk/licenses
License for package Android SDK Platform 30 accepted.
Preparing "Install Android SDK Platform 30 (revision: 3)".
"Install Android SDK Platform 30 (revision: 3)" ready.
Installing Android SDK Platform 30 in /Users/kshankar/Library/Android/sdk/platforms/android-30
"Install Android SDK Platform 30 (revision: 3)" complete.
"Install Android SDK Platform 30 (revision: 3)" finished.
```

There is one SDK

```
$ ls ~/Library/Android/sdk/platforms/
android-30
```

**Comment by shankari** [comment]
Upgraded to `compileSdk 31`. new SDK was downloaded but got the same error

```
Checking the license for package Android SDK Platform 31 in /Users/kshankar/Library/Android/sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /Users/kshankar/Library/Android/sdk/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.

An exception has occurred in the compiler (1.8.0_252). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
```

**Comment by shankari** [comment]
Upgrading to Java 11 as well compiles and runs. I had to rename `Android Studio` to `Android_Studio` to deal with path issues, but once I did that everything worked.

```
$ echo $JAVA_HOME
/Applications/Android_Studio.app/Contents/jre/Contents/Home

$ $JAVA_HOME/bin/java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7281165, mixed mode)

$ npx cordova build android
> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.3
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING:: Using flatDir should be avoided because it doesn't support any meta-data formats.

> Task :CordovaLib:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 22s
49 actionable tasks: 8 executed, 41 up-to-date
Built the following apk(s):
	/Users/kshankar/e-mission/native_code_upgrade/platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

**Comment by shankari** [comment]
If we go down this route, we will need to use java 11 in the CI.
On my laptop, I use the built-in java in Android Studio to get Java 11.
However, it looks like the Github virtual environments only install the android SDK, not android studio
https://github.com/actions/virtual-environments/blob/macOS-11/20211018.1/images/macos/macos-11-Readme.md

We would need to have separate setup scripts for CI and laptop that will set the JAVA_HOME differently. This sounds like a Bad Idea. Downloading JDK 11 from adoptjdk instead...

**Comment by asiripanich** [comment]
> from

Seems reasonable for me to drop support for phones with an Android version released 7 years ago. :0

**Comment by PatGendre** [comment]
> @PatGendre @jf87 @asiripanich @ericafenyo I am thinking of dropping support for android 5.0 It is the only version that still supports static permissions, so dropping it will simplify the codebase somewhat. By targeting API 23 instead of 22, we go from 92% support to 85% support, which doesn't seem like a lot. Thoughts?


@shankari yes it is reasonable to drop support for Android 5 if it makes thé upgrade easier

**Comment by shankari** [comment]
Implemented the new checks for the permissions auto-reset.
Works fine on both android 30 (apps restricted, need to unrestrict), and android 29 (`FEATURE_NOT_AVAILABLE`, apps unrestricted)

|   API     | OpenPATH | Settings
|--------|--------------|--------------|
| 30 | ![Screenshot_1635813608](https://user-images.githubusercontent.com/2423263/139768144-9118b5fc-fc47-4834-8b59-2607be51bf8d.png) | ![Screenshot_1635813654](https://user-images.githubusercontent.com/2423263/139768107-ffb836c5-ffdc-4463-a83a-5e7be6631f77.png) |
| 29 | ![Screenshot_1635813033](https://user-images.githubusercontent.com/2423263/139768133-6f3f453c-f801-47ec-af32-b492f78561b0.png) | ![Screenshot_1635813025](https://user-images.githubusercontent.com/2423263/139768121-16c8e7cd-4cc4-4559-ac75-bad135f15ff5.png) |

**Comment by shankari** [comment]
Moving on to the final two tasks for android:
- handle non-standard OEMs
- handle instead of having complicated logic in the background checks, just check for validity and then generate a notification that opens the status screen.

**Comment by shankari** [comment]
For the first one, there are at least two libraries that attempt to automate the process of launching the screen to fix the background settings.
1. https://github.com/judemanutd/AutoStarter
2. https://github.com/WanghongLin/CRomAppWhitelist

(1) supports more devices and has more forks and stars, but it appears to focus only on "AutoStart" settings. I have not seen any issues with push notifications, even on the Huawei from #677, the push notifications are always displayed. What we do have issues with is background optimizations. But the settings screens for both seem to be the same - e.g.
From https://github.com/WanghongLin/CRomAppWhitelist/blob/master/cromappwhitelist/src/main/assets/default_appwhitelist.json, the huawei background optimization setting is `"com.huawei.systemmanager.optimize.process.ProtectActivity"`, which is on the backup list for Huawei

Also, (2) only supports Chinese phones, so it doesn't support Samsung, which is the most common phone model that we have had issues with. In fact, it is the only model that we used to warn people about before.
https://github.com/e-mission/e-mission-phone/blob/master/www/js/intro.js#L52

```
      if($window.device.manufacturer.toLowerCase() == "samsung") {
        $scope.backgroundRestricted = true;
        $scope.allowBackgroundInstructions = $translate.instant("intro.allow_background.samsung");
      }
```

So we have to go with the first option, or something similar.
But the first option also has the problem that `"com.huawei.systemmanager.optimize.process.ProtectActivity"` is on the backup list for Huawei. So it may not be displayed if the first activity is available. But the first activity (`StartupNormalAppListActivity`) is not on the list for (2), even for autostart. And the activity in (2) for autostart (`BootStartActivity`) is not in the list for (1).

ARRGGHHH!

So it looks like we may want to try *both* libraries.

I also note that these may be more restrictive than we need. For example, the OnePlus is listed in (1), but we have reports from two OnePlus users that they don't have any issues. 
https://github.com/e-mission/e-mission-docs/issues/412#issue-453914743

So making users change settings unnecessarily during onboarding (or later!!) seems like a bad idea.

An alternate approach would be to use stats such as "number of periodic syncs" or "time delta during trip" to determine whether the app is working properly in the background. If it is not, then we ask the user to try various settings.

It would be great if we could record the finally selected settings, but in the absence of callbacks, I don't see an automated way to do that. Not sure if we can ask users to manually record that. We can certainly record whether or not changes were needed for a particular manufacturer/OS combination.

So this argues for the following design:
- we add a "yellow" section to the background restrictions asking people to check back in a day whether the background restrictions affect them
- in the non-onboarding status screen, we have some stats (that I will need to come up with) which indicate whether the background operation is not working properly. In that case, we will ask people to "fix" it by removing the background restrictions until the stats are green. We will then record (somewhere) that changing the background restrictions fixed the data collection on the app.

**Comment by shankari** [comment]
This seems super complicated, and potentially requires a new POST API or a new `user_input` or ???
Let's implement the second task on android and finish the implementation on iOS before tackling the first task.

**Comment by shankari** [comment]
One other issue on android: what if the user denies the permission?

I noticed this behavior while testing the motion activity permission on API level 30.

https://developer.android.com/training/permissions/requesting
> At the same time, your app should respect the user's decision to deny a permission. Starting in Android 11 (API level 30), if the user taps Deny for a specific permission more than once during your app's lifetime of installation on a device, the user doesn't see the system permissions dialog if your app requests that permission again. The user's action implies "don't ask again." On previous versions, users would see the system permissions dialog each time your app requested a permission, unless the user had previously selected a "don't ask again" checkbox or option.

https://user-images.githubusercontent.com/2423263/139960862-1dd2cf0b-f9e5-4e20-91d5-b52f66979700.mp4

Of course, even in previous versions, the user could select "Deny and don't ask again". We need to handle all of those. Let's do that first.

https://user-images.githubusercontent.com/2423263/139961392-acd6e247-c0b9-4da9-8013-62cf82712dff.mp4

**Comment by shankari** [comment]
Alas, it is non-trivial to fix this. The callback in both cases does not distinguish between "denied by user" and "denied automatically by system". In other words, when we call `requestPermissions`, we don't actually know whether the user will get a prompt to fix the situation or not. And if the permission is denied without showing them the prompt, they will not know what to do.

Let's explore the use of `shouldShowRequestPermissionRationale` (https://developer.android.com/reference/androidx/core/app/ActivityCompat#shouldShowRequestPermissionRationale(android.app.Activity,%20java.lang.String)) which is underdocumented.

**Comment by shankari** [comment]
Argh! This API is just bonkers. Apparently `shouldShowRequestPermissionRationale`:
- returns false before the first time the user prompts 
- returns true if the user used "Deny" and we are prompting again
- returns false if the user used "Deny and don't ask again"

The workaround on SO seems to be to store whether we have asked for this permission earlier or not!!

https://stackoverflow.com/questions/32347532/android-m-permissions-confused-on-the-usage-of-shouldshowrequestpermissionrati

**Comment by shankari** [comment]
Not quite sure how the flow will work for us in the second case, though given that our UI is not completely native.
- request permissions
- user denies, we say "please fix again"
- user fixes, we request permissions again
- user denies
   - we pop up the app settings screen in the native code?
      - user does nothing
      - what do we do now?
      - this option doesn't work
      - similar issues with deny, accept, deny since the check is for the lifetime of the app install

**Comment by shankari** [comment]
Another option might be to just always open the app permission settings. That would simplify the user interface. But it would also have a clunkier user interface for the case in which we could have the user accept the permission directly from the status screen.

**Comment by shankari** [comment]
we should also consider how to generate the local notification. 
1. What we really want to do is to call the `schedule` method in the plugin, but unfortunately, that is private. 
2. We considered calling `LocalNotify.execute` with the schedule parameters but it requires a cordovaCallback to work and since we click on the notification outside the cordova context, `cordovaCallback = null` in the when the click in processed in `onNewIntent`.

<img width="1113" alt="Screen Shot 2021-11-15 at 11 34 45 PM" src="https://user-images.githubusercontent.com/2423263/141940997-eee14d10-3a13-4a10-b7e1-3ddb778a29e5.png">
 
The next step is to call it directly using the notification manager in the local notification code. This is what we currently do in the transition notify code.
https://github.com/e-mission/e-mission-transition-notify/blob/4f32000935fe73f94d60ef68281eb2f3a343083a/src/android/TransitionNotificationReceiver.java#L172

TODO: Pull out the common dispatch functionality to NotificationHelper or similar so we can generate local notifications from anywhere in our codebase.

**Comment by shankari** [comment]
Pulled out the common dispatch functionality, but haven't yet converted the TripEnd notification code to use the new functionality, since I don't have an easy way to test it right now. We also don't know whether we want to retain the trip end notification code since it has not been very widely used so far.

Filed issue to clean it up https://github.com/e-mission/e-mission-transition-notify/issues/32

**Comment by shankari** [comment]
Changes for background sensing done. In addition to the data collection plugin, also needed changes to:
https://github.com/e-mission/cordova-unified-logger/pull/35
and
https://github.com/e-mission/cordova-usercache/pull/43

**Comment by shankari** [comment]
Integrated the app status (at least in basic fashion) into the control screen.
Now if I can just have the modal popup automatically when the user clicks on the notification, this is demo-worthy.

**Comment by shankari** [comment]
Tried creating a new state with the same controller and view

```
  .state('root.main.control.appstatus', {
    url: '/control/appstatus',
    views: {
      'main-control': {
        templateUrl: 'templates/control/main-control.html',
        controller: 'ControlCtrl'
      }
    }
  })
```

and then redirecting to it. But this naive approach doesn't work since 

```
ionic.bundle.js:26794 Error: Could not resolve 'root.main.control.appstatus ' from state 'root.main.control'
    at Object.transitionTo (ionic.bundle.js:52013)
    at Object.go (ionic.bundle.js:51946)
    at Object.localNotify.handleLaunch (localnotify.js:28)
    at localnotify.js:52
    at processQueue (ionic.bundle.js:29127)
    at ionic.bundle.js:29143
    at Scope.$eval (ionic.bundle.js:30395)
    at Scope.$digest (ionic.bundle.js:30211)
    at ChildScope.$apply (ionic.bundle.js:30503)
    at HTMLButtonElement.<anonymous> (ionic.bundle.js:65426)
```

switching back to a single state, but with the params defined outside the URL https://github.com/angular-ui/ui-router/wiki/URL-Routing#using-parameters-without-specifying-them-in-state-urls

```
  .state('root.main.control', {
    url: '/control',
    params: {
        launchAppStatusModal: false
    },
    views: {
      'main-control': {
        templateUrl: 'templates/control/main-control.html',
        controller: 'ControlCtrl'
      }
    }
```

Bingo!! That worked!!

```
afterEnter called with stateparams launchAppStatusModal: false
afterEnter called with stateparams launchAppStatusModal: true
```

**Comment by shankari** [comment]
At this point, the code is good enough for demo purposes but there are still some hacks that need to be investigated/fixed:
- overallAppStatus on the profile page is not getting updated
- seemingly infinite loop between `waiting_for_trip_start` and `tracking_error` when the motion activity is turned off
- local notification callbacks not invoked if app has been killed/restarted versus just resumed
- cancelling notifications by ID does not work, only `cancelAll`

But it is probably good enough to push out as a beta version and get feedback.

**Comment by shankari** [comment]
One more issue: The hook to rewrite the package name for `R` does not seem to work for the new file `/Users/kshankar/e-mission/e-mission-phone/plugins/cordova-plugin-em-datacollection/src/android/verification/SensorControlChecks.java`

```
walk callback with files = ..../Users/kshankar/e-mission/e-mission-phone/plugins/cordova-plugin-em-datacollection/src/android/verification/SensorControlChecks.java...

file SensorControlBackgroundChecker.java needs to be rewritten, checking package
Handling package: edu.berkeley.eecs.emission.cordova.tracker.verification
sourceFile: /Users/kshankar/e-mission/e-mission-phone/platforms/android/app/src/main/java/edu/berkeley/eecs/emission/cordova/tracker/verification/SensorControlBackgroundChecker.java
file SensorControlForegroundDelegate.java needs to be rewritten, checking package
Handling package: edu.berkeley.eecs.emission.cordova.tracker.verification
sourceFile: /Users/kshankar/e-mission/e-mission-phone/platforms/android/app/src/main/java/edu/berkeley/eecs/emission/cordova/tracker/verification/SensorControlForegroundDelegate.java
```

Manually fixing and moving on for now..

We should also add a reconfigured build to the CI to catch this in the future.

**Comment by shankari** [comment]
Another huge issue is that we appear to get a tracking_error generated at app launch. This generates a weird error message and a message saying that we need to click on it to resolve!! And the message is never removed, even after the user fixed everything and consents.

Tried multiple times to figure out where we are getting the tracking error from, but no luck in the time available. Hacking around this for now by making changes only to `markConsented` but need to figure out the whole init workflow and streamline it.

**Comment by shankari** [comment]
Added hack

<details>
<summary> Hack details </summary>

```
diff --git a/src/android/DataCollectionPlugin.java b/src/android/DataCollectionPlugin.java
index 771e4f9..ed40ca1 100644
--- a/src/android/DataCollectionPlugin.java
+++ b/src/android/DataCollectionPlugin.java
@@ -1,7 +1,10 @@
 package edu.berkeley.eecs.emission.cordova.tracker;

+import de.appplant.cordova.plugin.notification.Manager;
 import edu.berkeley.eecs.emission.R;

+
+
 import org.apache.cordova.CordovaPlugin;
 import org.apache.cordova.CordovaInterface;
 import org.apache.cordova.CallbackContext;
@@ -64,12 +67,14 @@ public class DataCollectionPlugin extends CordovaPlugin {
             JSONObject newConsent = data.getJSONObject(0);
             ConsentConfig cfg = new Gson().fromJson(newConsent.toString(), ConsentConfig.class);
             ConfigManager.setConsented(ctxt, cfg);
-            TripDiaryStateMachineForegroundService.startProperly(cordova.getActivity().getApplication());
+            Manager nMgr = Manager.getInstance(cordova.getActivity());
+            nMgr.cancelAll();
             // Now, really initialize the state machine
             // Note that we don't call initOnUpgrade so that we can handle the case where the
             // user deleted the consent and re-consented, but didn't upgrade the app
             // mControlDelegate.checkAndPromptPermissions();
-            // ctxt.sendBroadcast(new ExplicitIntent(ctxt, R.string.transition_initialize));
+            ctxt.sendBroadcast(new ExplicitIntent(ctxt, R.string.transition_initialize));
+            TripDiaryStateMachineForegroundService.startProperly(cordova.getActivity().getApplication());
             // TripDiaryStateMachineReceiver.restartCollection(ctxt);
             callbackContext.success();
             return true;
```

</details>

**Comment by shankari** [comment]
Feedback from Sandee:
- add a sentence asking people to make sure everything is green
- truncate description of background location

**Comment by shankari** [comment]
After many months, and fixing a couple of side issues (https://github.com/e-mission/e-mission-phone/pull/804/commits/4378a70d9638f0e2bf6647c180d95e3061dcbbe4, https://github.com/e-mission/e-mission-phone/pull/805, https://github.com/e-mission/e-mission-phone/pull/808, https://github.com/e-mission/e-mission-phone/pull/809) let's return here and:
- fix pending issues on android
- implement on iOS

**Comment by shankari** [comment]
Starting with https://github.com/e-mission/e-mission-docs/issues/680#issuecomment-971825731, the hook searches for 

```
const R_RE = /[^\.\w]R\./;
...
                        if (contents.match(R_RE) || contents.match(BUILDCONFIG_RE) || contents.match(MAINACT_RE)) {
                            console.log('file '+filename+' needs to be rewritten, checking package');
```

but the R package is actually unused in `SensorControlChecks.java`. So there is no `R.` and the match fails. The solution is to remove the unused import.

**Comment by shankari** [comment]
wrt

> Will check in and publish tomorrow and then try to debug the case of the app status icon in the profile page.

not sure what the problem with the app status icon on the profile page is

**Comment by shankari** [comment]
I looked into it a little more, and we do in fact compute the `overallAppStatus in the app status directive controller. However, because it is not correctly linked to the `overallAppStatus` field in the profile scope, nothing gets updated correctly. I'm going to try one more time to fix it, but otherwise, I am moving on.

Note that the `overallAppStatus` in the directive appears to be correct, so if I change the onClick to `ng-click="appStatusChecked(overallAppStatus)"` and add a new line in the callback, the status is updated correctly. Need to figure out whether we can return any value during modal initialization.

```+        $scope.overallAppStatus = newStatus;
```

**Comment by shankari** [comment]
I tried to read the value from the modal once it was created. Unfortunately, the modal is returned before the status is recomputed.

I then added a breakpoint into another function and invoked if after the modal was initialized. The `overallAppStatus` still had it as `false`.

**Comment by shankari** [comment]
> seemingly infinite loop between waiting_for_trip_start and tracking_error when the motion activity is turned off

we should definitely fix this and 

> Another huge issue is that we appear to get a tracking_error generated at app launch. This generates a weird error message and a message saying that we need to click on it to resolve!! And the message is never removed, even after the user fixed everything and consents.

and then I think we should move on to iOS

**Comment by shankari** [comment]
We start the periodic sync

```
2021-07-27 16:12:45.427 22374-22921/edu.berkeley.eecs.emission I/TripDiaryStateMachineRcvr: START PERIODIC ACTIVITY
```

Foreground service starts

```
2021-07-27 16:12:49.795 22374-22921/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: startProperly called with context = edu.berkeley.eecs.emission.MainActivity@b3efb44
2021-07-27 16:12:49.828 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onCreate called
2021-07-27 16:12:49.842 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onStartCommand called with intent = Intent { cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineForegroundService } flags = 0 and startId = 1
```

We generate an "initialize"

```
      TripDiaryStateMachineForegroundService.startProperly(ctxt);
      // It is not enough to move to the foreground; you also need to reinitialize tracking
      // https://github.com/e-mission/e-mission-docs/issues/580#issuecomment-700747931
      ctxt.sendBroadcast(new ExplicitIntent(ctxt, R.string.transition_initialize));
```

And we launch a bunch of checks for the app state

```
        if (intent == null) {
          SensorControlBackgroundChecker.checkAppState(this);
          message = humanizeState(this, TripDiaryStateMachineService.getState(this));
        }
```

So far, so good.

The checks indicate that motion activity is turned off and so we generated
another notification to fix it.

```
2021-07-27 16:12:51.637 22374-22921/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: Curr status check results =  loc permission, motion permission, notification, unused apps [true, false, true, true]
2021-07-27 16:12:51.780 22374-22921/edu.berkeley.eecs.emission D/NotificationHelper: Generating notify with id 362253739, message Click to view and fix app status and pending intent PendingIntent{1278d18: android.os.BinderProxy@3649371}
```

We receive and handle the initialize, note that it uses a new thread (22374-22374)

```
2021-07-27 16:13:04.370 22374-22374/edu.berkeley.eecs.emission I/TripDiaryStateMachineRcvr: TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@eaf447e, Intent { act=local.transition.initialize flg=0x10 pkg=edu.berkeley.eecs.emission cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called
2021-07-27 16:13:16.758 22374-22921/edu.berkeley.eecs.emission I/TripDiaryStateMachineRcvr: END PERIODIC ACTIVITY
```

We generate another start command because we received the initialize

```
if (intent.getAction().equals(context.getString(R.string.transition_initialize))) {
    ...
    TripDiaryStateMachineForegroundService.startProperly(context);
}
```

```
2021-07-27 16:13:19.818 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: startProperly called with context = android.app.ReceiverRestrictedContext@eaf447e
2021-07-27 16:13:25.027 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onStartCommand called with intent = Intent { cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineForegroundService } flags = 0 and startId = 2
```

**Step 1: We should consider removing this circular dependency.**
- When we find that the foreground service notification does not exist (in
  `checkForegroundNotification`):
    - we re-generate initialize
    ```
          TripDiaryStateMachineForegroundService.startProperly(ctxt);
          // It is not enough to move to the foreground; you also need to reinitialize tracking
          // https://github.com/e-mission/e-mission-docs/issues/580#issuecomment-700747931
          ctxt.sendBroadcast(new ExplicitIntent(ctxt, R.string.transition_initialize));
    ```
    - when the initialize is received, we start the service
    ```
    if (intent.getAction().equals(context.getString(R.string.transition_initialize))) {
        ...
        TripDiaryStateMachineForegroundService.startProperly(context);
    }
    ```
    Fortunately, in `startProperly`, we don't re-send the initialize, but this
        callback seems unnecessary. From my last minute frantic debugging, this
might also be the reason for
https://github.com/e-mission/e-mission-docs/issues/680#issuecomment-971953421

Let's revert the hack, see if this is the case and then see how to fix it.

**Comment by shankari** [comment]
reverted hack and fixed, picking back up on infinite loop
- circular dependency is annoying but it is not a deal-breaker. A potential fix would be to pass in the location that the initialize was generated from, and skip calling `startProperly` if the initialize was generated from the foreground service. But let's fix the actual problem first, and then work on the niceties.

**Comment by shankari** [comment]
Picking up after the startProperly call, we restart the service


```
2021-07-27 16:13:25.027 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onStartCommand called with intent = Intent { cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineForegroundService } flags = 0 and startId = 2
```

Next, we handle the initialize and begin re-creating the geofence

```
2021-07-27 16:13:25.272 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: handleAction(local.state.waiting_for_trip_start, local.transition.initialize) called
...
2021-07-27 16:13:25.661 22374-22983/edu.berkeley.eecs.emission D/CreateGeofenceAction: About to start waiting for location
```

In parallel, we start handling the `tracking_error` that we generated earlier from the checkAppStatus after re-creating the foreground service.

```
2021-07-27 16:13:56.783 22374-22374/edu.berkeley.eecs.emission I/TripDiaryStateMachineRcvr: TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@eaf447e, Intent { act=local.transition.tracking_error flg=0x10 pkg=edu.berkeley.eecs.emission cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called
```

we get back the location and create the geofence


```
2021-07-27 16:15:37.512 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState saved in prefManager is local.state.waiting_for_trip_start
```

as part of the regular checks after setting the state, we notice that the
motion activity is bad, so we set the new state to start

```
2021-07-27 16:16:39.656 22374-22374/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: Curr status check results =  loc permission, motion permission, notification, unused apps [true, false, true, true]
2021-07-27 16:16:41.331 22374-22374/edu.berkeley.eecs.emission D/NotificationHelper: Generating notify with id 362253739, message Click to view and fix app status and pending intent PendingIntent{280b2ec: android.os.BinderProxy@5d846b5}
2021-07-27 16:17:30.871 22374-22374/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState after handling action is local.state.start
```

Then we check the settings again

```
2021-07-27 16:17:34.264 22374-22374/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: Curr status check results =  loc permission, motion permission, notification, unused apps [true, false, true, true]
2021-07-27 16:17:34.448 22374-22374/edu.berkeley.eecs.emission D/NotificationHelper: Generating notify with id 362253739, message Click to view and fix app status and pending intent PendingIntent{54c7384: android.os.BinderProxy@5d846b5}
```

But now we are in the start state, so we restart the FSM by generating an initialize

```
2021-07-27 16:17:34.471 22374-22374/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: in restartFSMIfStartState, currState = local.state.start
2021-07-27 16:17:34.483 22374-22374/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: in start state, sending initialize
```

So the loop is:
- initialize when motion activity is turned off
- try to create geofence, succeeds, move to `waiting_for_trip_start`
- in `setNewState`, check settings, find that motion activity is a problem,
  generate `tracking_error`, move to `start` state
- in `setNewState`, check settings, find that motion activity is a problem,
  try to restart the FSM by generating an initialize because we are in start state
- try to create geofence, succeeds, move to `waiting_for_trip_start`

The real problem is that we are in two minds about how to treat non location permissions. In the FSM, we treat them as optional, so once the geofence is created, we go to `waiting_for_trip_start`. In the sensor control checks, we treat them as required, so we generate a tracking error if they are not present.

We need to figure out how we want to represent these. This will involve community input, so I have created https://github.com/e-mission/e-mission-docs/issues/700 to track it. For now, we will treat them as optional, which means that we only need to generate a tracking error if the location is turned off.

**Comment by shankari** [comment]
Last remaining issues on android: 
- local notification callbacks not invoked if app has been killed/restarted versus just resumed
- formatting/text changes

**Comment by shankari** [comment]
wrt
> local notification callbacks not invoked if app has been killed/restarted versus just resumed

this is because when we generate the notification from `SensorControlBackgroundChecker.generateOpenAppSettingsNotification`, we do so with the `MainActivity`.

We expect to get a callback in `DataCollectionPlugin.onNewIntent`, which will then, in `SensorControlForegroundDelegate.onNewIntent` schedule a second plugin compatible notification.

The problem is that the first intent invokes the main activity which already launches the app, before the second notification is generated. We then end up with two notifications with the same message.

Clicking on the original notification again generates a `trigger` event since the app is already running so it works.
This also explains why the notification is not cancelled when the user clicks on it - it is not plugin-scheduled notification.

Adding additional messages to the notifications generated from the two separate locations clarifies this.

In the video below:
- turn off activity permission
- see the "opens main" notification
- click it; app launches again
- at 0:22, the plugin-compatible notification (with a circle) is generated
- see the "plugin-compatible" notification
- click on "opens main", event is received by javascript but notification is not cancelled
- click on "plugin-compatible", event is received by javascript and notification is cancelled


https://user-images.githubusercontent.com/2423263/152728246-3a7d1558-b042-4a55-a751-b608d8fadf73.mp4

**Comment by shankari** [comment]
Tried to fix this by generating the "from plugin" notification directly. This now shows up as soon as the motion activity permission is removed. However, clicking it still does not generate the notifications.

This is because the local notification callback 

```
  localNotify.registerRedirectHandler = function() {
    Logger.log( "registerUserResponse received!" );
....
}
```

is called at 21:25 

```
2022-02-06 21:25:24.870 24517-24517/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:registerUserResponse received!", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-06 21:25:25.038 24517-24517/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:registerUserResponse received!", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
```

after the event is fired

```
2022-02-06 21:25:24.609 24517-24517/edu.berkeley.eecs.emission D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.notification.local.fireEvent("click",{"id":362253744,"title":"Incorrect app settings plugin-compatible","text":"Click to view and fix app status plugin-compatible","data":{"redirectTo":"root.main.control","redirectParams":{"launchAppStatusModal":true}},"trigger":{"type":"calendar"},"progressBar":{"enabled":false}},{"event":"click","foreground":false,"queued":true,"notification":362253744}))
```

This is the full history

```
2022-02-06 21:45:53.880 4249-4249/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY onCreate called
2022-02-06 21:45:53.936 4249-4249/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY onResume called
2022-02-06 21:45:58.159 4249-4587/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, sending pending javascript
2022-02-06 21:45:58.159 4249-4587/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, finished sending pending javascript
2022-02-06 21:45:58.204 4249-4249/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY ionicPlatform is ready in the app", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-06 21:45:58.263 4249-4249/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY ionicPlatform is ready in the app", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-06 21:45:58.483 4249-4249/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY received ready, registering handlers", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-06 21:45:58.551 4249-4249/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY received ready, finished registering handlers", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
```

**Comment by shankari** [comment]
Ah, the documentation says: https://github.com/katzer/cordova-plugin-local-notifications#launch-details
> It might be possible that the underlying framework like Ionic is not compatible with the launch process defined by cordova. > With the result that the plugin fires the click event on app start before the app is able to listen for the events.
> Therefore its possible to fire the queued events manually by defining a global variable.

```
window.skipLocalNotificationReady = true
```

> Once the app and Ionic is ready, you can fire the queued events manually.

```
cordova.plugins.notification.local.fireQueuedEvents();
```

**Comment by shankari** [comment]
After those changes, the logs are:

```
2022-02-07 11:58:00.592 21780-21780/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY onCreate called
2022-02-07 11:58:00.631 21780-21780/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY onResume called
2022-02-07 11:58:04.761 21780-21780/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY ionicPlatform is ready in the app", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-07 11:58:04.820 21780-21780/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY ionicPlatform is ready in the app", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-07 11:58:05.021 21780-21780/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY received ready, registering handlers", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-07 11:58:05.081 21780-21780/edu.berkeley.eecs.emission I/chromium: [INFO:CONSOLE(49)] "DEBUG:LOCAL NOTIFY received ready, finished registering handlers", source: https://localhost/plugins/cordova-plugin-em-unifiedlogger/www/unifiedlogger.js (49)
2022-02-07 11:58:05.109 21780-22039/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, sending pending javascript
2022-02-07 11:58:05.109 21780-22039/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, finished sending pending javascript
2022-02-07 11:58:18.013 21780-21780/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, sending pending javascript
2022-02-07 11:58:18.013 21780-21780/edu.berkeley.eecs.emission I/LOCAL NOTIFICATION: LOCAL NOTIFY: deviceready called, finished sending pending javascript
```

and the operation is correct


https://user-images.githubusercontent.com/2423263/152870599-5d3808d9-9834-480b-9337-ca38eaf63dd1.mp4

**Comment by shankari** [comment]
Publishing new version on android and then moving on to making the same changes on iOS...
Will clean up components after iOS changes.

**Comment by shankari** [comment]
Turning off activity permissions works, but turning off location goes back to our infamous infinite loop. So near and yet so far...

In this case, because the location permission is turned off, we actually end up staying in the start state.

```
2022-02-07 23:24:30.754 12834-12834/edu.berkeley.eecs.emission I/TripDiaryStateMachineRcvr: TripDiaryStateMachineReciever onReceive(android.app.ReceiverRestrictedContext@eae6be5, Intent { act=local.transition.tracking_error flg=0x10 pkg=edu.berkeley.eecs.emission cmp=edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineReceiver }) called
2022-02-07 23:24:30.771 12834-12834/edu.berkeley.eecs.emission I/TripDiaryStateMachineService: Service destroyed. So long, suckers!
2022-02-07 23:24:30.795 12834-12834/edu.berkeley.eecs.emission I/TripDiaryStateMachineService: Service created. Initializing one-time variables!
2022-02-07 23:24:30.803 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: service started with flags = 0 startId = 1 action = local.transition.tracking_error
2022-02-07 23:24:30.812 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: after reading from the prefs, the current state is local.state.start
2022-02-07 23:24:30.841 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: handleAction(local.state.start, local.transition.tracking_error) called
2022-02-07 23:24:30.865 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: TripDiaryStateMachineReceiver handleStarted(local.transition.tracking_error) called
2022-02-07 23:24:30.872 12834-12834/edu.berkeley.eecs.emission I/TripDiaryStateMachineService: Already in the start state, so going to stay there
2022-02-07 23:24:30.880 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState after handling action is local.state.start
2022-02-07 23:24:30.892 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState saved in prefManager is local.state.start
2022-02-07 23:24:30.907 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: handleAction(local.state.start, local.transition.tracking_error) completed, waiting for async operations to complete
```

But we stay in the start state by calling `setState(start)` which triggers the checks

```
                                    Log.e(fCtxt, TAG, "error while creating geofence, staying in the current state");
                                    Log.exception(fCtxt, TAG, task.getException());
                                    setNewState(mCurrState, true);
...
        if (doChecks) {
            SensorControlBackgroundChecker.checkAppState(TripDiaryStateMachineService.this);
        }
```

which generates an initialize 

```
2022-02-07 23:25:05.750 12834-12834/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: in start state, sending initialize
```

and so on, ad inifinitum

```
2022-02-07 23:24:32.213 29553-29570/? W/GLMSImpl: edu.berkeley.eecs.emission doesn't have sufficient location permission to request geofence.
2022-02-07 23:24:32.221 12834-12834/edu.berkeley.eecs.emission E/TripDiaryStateMachineService: error while creating geofence, staying in the current state
2022-02-07 23:24:32.233 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState after handling action is local.state.start
2022-02-07 23:24:32.241 12834-12834/edu.berkeley.eecs.emission D/TripDiaryStateMachineService: newState saved in prefManager is local.state.start
...
2022-02-07 23:24:32.374 12834-12834/edu.berkeley.eecs.emission I/SensorControlBackgroundChecker: Curr status check results =  loc permission, motion permission, notification, unused apps [false, true, true, true]
```

**Comment by shankari** [comment]
Calling `restartFSMIfStartState` only if we have adequate permissions should solve this problem. If we know that there are problems with the permissions, there's no point in trying to initialize the FSM. Tried this, and the FSM gets stuck in the start state. Why doesn't the foreground service restart call initialize and wake it up?

Looks like the foreground service is destroyed 

```
2022-02-08 00:16:25.182 2068-2088/? W/ActivityManager: Scheduling restart of crashed service edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineForegroundService in 1000ms
2022-02-08 00:16:26.199 2068-2848/? W/ActivityManager: Stopping service due to app idle: u0a154 -26m37s622ms edu.berkeley.eecs.emission/.cordova.tracker.location.TripDiaryStateMachineForegroundService
2022-02-08 00:16:26.242 2068-2099/? I/ActivityManager: Start proc 30782:edu.berkeley.eecs.emission/u0a154 for service {edu.berkeley.eecs.emission/edu.berkeley.eecs.emission.cordova.tracker.location.TripDiaryStateMachineForegroundService}
2022-02-08 00:16:27.017 30782-30782/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onCreate called
2022-02-08 00:16:27.029 30782-30782/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onDestroy called for foreground service
2022-02-08 00:16:27.039 30782-30782/edu.berkeley.eecs.emission D/TripDiaryStateMachineForegroundService: onDestroy called, removing notification
```

**Comment by shankari** [comment]
<img width="1221" alt="Screen Shot 2022-02-08 at 10 11 13 AM" src="https://user-images.githubusercontent.com/2423263/153049628-a7119830-5f5e-44d6-89d1-d628b7ee909f.png">
<img width="1221" alt="Screen Shot 2022-02-08 at 10 11 46 AM" src="https://user-images.githubusercontent.com/2423263/153049789-80b6c18c-0022-46d4-82c3-a099b82b4cbd.png">

**Comment by shankari** [comment]
So the problem is that in the initial FSM, we are polling continuously. Which allows us to find that the permission has been reinstated, but is terrible from a performance perspective and from an "app doesn't appear to be broken" perspective.
We can remove the continuous polling by removing the reinitialize from within the check permissions. But then we need to be notified when the value has changed.

This is non-trivial because we don't always get a callback when the permissions have changed. So we need to handle the common case and move on.
- Common case: permissions are fixed from the app UI - if the onboarding is complete, then check status again
- Uncommon case: permissions are fixed from the app settings - will pick up during periodic check
<img width="1221" alt="Screen Shot 2022-02-08 at 11 00 29 AM" src="https://user-images.githubusercontent.com/2423263/153057007-c394d35b-4f29-4717-af78-9f951a145078.png">

**Comment by shankari** [comment]
Just to finish testing this:

### location settings
- status screen green
- turn off location
- force sync -> see error notification **but "ready to start trip"**
- click on error notification
- open status screen
- enable location
- "I accept" -> error notification goes away, Ready for trip
- **disable again and go through the process, when status screen opens, Location settings is green**

### location permission
- status screen green
- turn off location permission
- app auto-restarts -> see error notification after some moving back and forth
- click on error notification
- open status screen
- enable location permission
- "I accept" -> error notification goes away, Ready for trip

### activity permission
- status screen green
- turn off location permission
- app auto-restarts -> see error notification after some moving back and forth
- click on error notification
- open status screen
- enable location permission
- "I accept" -> error notification goes away, Ready for trip

**Comment by shankari** [comment]
The minor inconsistencies with the location settings (highlighted in bold above) are because it is an async call. So:
- we don't generate a `tracking_error`, which in turn means that the state remains in `waiting_for_trip_start`
- when location is turned off, the app is not killed and restarted, which means that the controller is not re-initialized and the settings are unchanged.

Once we fix those, we are really done.

**Comment by shankari** [comment]
The challenge is that the settings check comes with a callback so it doesn't happen at the same time as the permission checks. We can generate a `tracking_error` from the callback as well, 

```
    private static void checkLocationSettings(final Context ctxt) {
      SensorControlChecks.checkLocationSettings(ctxt, resultTask -> {
          try {
          } catch (ApiException exception) {
            ctxt.sendBroadcast(new ExplicitIntent(ctxt, R.string.transition_tracking_error)); // new code
            generateOpenAppSettingsNotification(ctxt);
            }
        });
    }
```

but when we generate the initialize once the permission checks all pass as well, 

```
      if (allOtherChecksPass) {
        Log.d(ctxt, TAG, "All permissions (except location settings) valid, nothing to prompt");
        restartFSMIfStartState(ctxt);
      }
```

which leads to our infamous infinite loop from 
https://github.com/e-mission/e-mission-docs/issues/680#issuecomment-1032915223

We really need to treat the location settings as a required check. Which means that we need to have the results along with the permission check results. We can probably do some task-related magic to make this happen, but the easiest option is probably to just inline the callback.

**Comment by shankari** [comment]
Switched to an instance class in https://github.com/e-mission/e-mission-data-collection/pull/195/commits/b7ff5d6a3ee9df7b1cb7572f25a6625792a9d68d

Even after switching to instance classes, this is a bit tricky since the callback is in a different class, and not the same class. And our desired behavior is different depending on whether the change was part of a user-initiated operation or not.
- if it is part of a user-initiated operation, we want to return the result to the user. We don't want to generate a new notification telling them to open the status screen, specially if they haven't even finished onboarding yet
- if it is part of separate change later, we want to generate a notification for them to open the status screen and fix the issue.

Note that difference here is user-initiated vs. background, not onboarding vs. later. If the user attempts to fix the permission from the status screen months after installation, they don't want to see a weird notification either. This is actually not a problem if the permission is correct - we will cancel the notification first anyway.

But if the permission is incorrect, then showing another notification would be bad. Because the app is already open, this would be another "trigger", which would generate an in-app popup.

Note also that we currently get a callback on app start (before first page is shown) that I can only see with a breakpoint. 

```
```

This makes me nervous about timing issues wrt state during app start. We can't afford to have false positives wrt errors. It might lead to a "cry wolf" syndrome where people ignore the notifications since they show up so often.

So ideally, the TripDiaryDelegate would store the information about whether call was from the foreground or not. Note that if it is, it would need to send a callback to the ForegroundDelegate so it could use the correct commandID to respond to the user.
 
Both delegates are instances, not classes, so we cannot easily make static calls back and forth.

The cleanest solution seems to be for the ForegroundDelegate to let the TripDiaryDelegate know about itself. The TripDiaryDelegate can then call it if it exists, or call the background checker otherwise.

The foreground delegate can notify the TripDiaryDelegate about itself in one of two ways:
- it can make a static call to the TripDiaryDelegate's `TripDiaryDelegatePermissions` category to "register" itself. The static call would get the current `TripDiaryStateMachine` instance, get its delegate, and then register itself there.
- we can use an event-based architecture where it sends an event and the delegate registers itself.

Let's go with the static method approach since it seems simpler.

**Comment by shankari** [comment]
Actually, the static method approach will not work. The static call can get the current `TripDiaryStateMachine` instance but the delegate property of the instance is not public. If it were public, we would not need the static method because we could call the `TripDiaryStateMachine` directly.

The event-based architecture also has a problem around where we can register for the event. If we do so in the main class `init`, then it breaks the decoupling of the permission stuff. There is no other place we can do it where we can access an instance variable.

A simpler option might be to expose the delegate from the `TripDiaryStateMachine`. Since there is only one TSDM and one delegate, this should allow us to treat the delegate as a singleton and will make message passing much simpler.

**Comment by shankari** [comment]
> Note also that we currently get a callback on app start (before first page is shown) that I can only see with a breakpoint.

I was worried about this and wondered whether we need to store state on `intro_done` versus not. The truth table would then be:

| from_plugin | intro_done |  task |
|------------|------------|------|
|        T         |        x          |   callback        |
|        F         |        F          |   ignore (startup call before user acceptance)        |
|        F         |        T          |   generate notification        |

However, it turns out that in the (F, F) case, the user has also not accepted the notification permission, so the notification does not show up 😄 

So our simplified truth table is:

| from_plugin | intro_done |  task |
|------------|------------|------|
|        T         |        x          |   callback        |
|        F         |        F          |   generate notification but it will not be visible (startup call before user acceptance)        |
|        F         |        T          |   generate notification        |

which simplifies to

| from_plugin | intro_done |  task |
|------------|------------|------|
|        T         |        x          |   callback        |
|        F         |        x          |   generate notification |

which simplifies to

| from_plugin | task |
|------------|------------|------|
|        T         |  callback        |
|        F         |  generate notification |

**Comment by shankari** [comment]
The motion activity stuff doesn't have callbacks, so we tried to make some to at least cover the common case of prompting the user when the value is not determined.

Current behavior:
- (common case) New install, user selects "Allow": Status turns green
- (less common case) New install, user selects "Don't Allow":
   - Status says red, prompt to fix in app settings
   - Hit "fix" again, open app settings
   - Enable settings; app `Terminated due to signal 9`
   - select emission from history
   - process restarted from scratch
   - come to status screen, status is green
     - this is a little clunky, but I guess it works
     - no way to avoid it; app is terminated when settings are changed, similar to android (https://stackoverflow.com/a/49337938/4040267).
     - Only seems to happen for motion activity, similar flow in location does not appear to kill the app
     - changed location settings multiple times to no effect
- (way less common case) New install, settings turned off
   - prompt to enable motion activity settings
   - enable, click icon to relaunch, still on status screen, still red
   - click "fix", still says to enable motion activity settings
   - could not connect to debugger to determine the issue
   - this is not 100% reproducible; tried again and it worked
   - working scenario: app is killed when settings are enabled; restarted when reopened and then the new status is returned.
   - need to try carefully and check how many times each scenario happens; presumably while not connected to the debugger
  
**Reproducing the bad state**
The app doesn't even show up as having requested access to the activity.

| No activity access | In the app either | Until we request access? |
|------|--------|-------|
| <img width="375" alt="image" src="https://user-images.githubusercontent.com/2423263/154174735-29ba0c63-22ce-40b0-b2da-f75253adbd5e.png"> | <img width="375" alt="image" src="https://user-images.githubusercontent.com/2423263/154174791-b22cec60-c54b-4bae-9f3c-5219f9fc5d74.png"> | <img width="375" alt="image" src="https://user-images.githubusercontent.com/2423263/154174853-95dbca8e-14d6-4cad-aca3-50595293984e.png">

**Comment by shankari** [comment]
After enabling notification permissions, we are almost done. Except for one really bizarre issue. On iOS13, when we open the app settings, the location permission is not visible. After a few hours spent debugging this, the situation is:
- went back to https://github.com/e-mission/e-mission-data-collection/pull/195/commits/ca979bd85f585161cdb387687bbd2acba4f3cb85, still broken
- tried to run on older versions of the emulator, still broken
- went back to the version before the native code upgrade - e.g. https://github.com/e-mission/e-mission-data-collection/releases/tag/v1.6.0 and it finally worked

So my current thoughts are:
- I guess I tested https://github.com/e-mission/e-mission-data-collection/pull/195/commits/ca979bd85f585161cdb387687bbd2acba4f3cb85 on the physical phone, running 12.x and not on 15.x
- there is something in the old app code which indicates that we need locations, similar to the activity sensor to indicate that the app is requesting a location. That code path is triggered in the old version and not the old version. We need to figure that out, add it and then we are really done.

**Comment by shankari** [comment]
@PatGendre @ericafenyo @lgharib I have just finished an initial version of the status screen. I will likely tweak it going forward, but wanted to get it out of the door for feedback.

I would encourage you to test it out, provide feedback and then update your versions of the apps. It is likely to make it easier to install correctly and to keep the app running correctly - e.g. solve the "iOS reset permissions" issue.

@ericafenyo this involves a significant expansion of the interface for the data collection library/plugin and a new UI screen. The new interface is fairly simple, mainly consisting of `fixXXX` and `isValidXXX`, but let me know if you have any questions.

**Comment by shankari** [comment]
@asiripanich I just pushed the new iOS version to TestFlight in case you want to take a look. Open to feedback on other status metrics to include.

**Comment by shankari** [comment]
The status screen opens from the profile. You should also experiment with turning various permissions off and seeing what happens 😄

**Comment by ericafenyo** [comment]
> this involves a significant expansion of the interface for the data collection library/plugin and a new UI screen. The new interface is fairly simple, mainly consisting of fixXXX and isValidXXX, but let me know if you have any questions.

Ok I will test and let you know when I have questions. Thanks.

**Comment by asiripanich** [comment]
> the

I will do that and report back today. :)

**Comment by asiripanich** [comment]
@shankari I like the new permission status screen. However, the scrolling issue is still there (we discussed it somewhere but I can't find the related issue).

**Comment by shankari** [comment]
@asiripanich can you elaborate more on the scrolling issue? Some context may help me find the related issue.

**Comment by shankari** [comment]
@asiripanich note also that the permission status screen is not only for onboarding. We also use it to track the status on an ongoing basis. If the user responds to the "XXX has been using your location in the background, do you want to continue?" with "no", then we will prompt the user that the app settings are incorrect, and open the app settings screen when they click on the notification so they can fix the issue easily.

I encourage you to experiment with turning location settings/permissions on/off, motion activity settings off, etc to see this behavior and whether it makes sense.

**Comment by PatGendre** [comment]
> @PatGendre @ericafenyo @lgharib I have just finished an initial version of the status screen. I will likely tweak it going forward, but wanted to get it out of the door for feedback.
> 
> I would encourage you to test it out, provide feedback and then update your versions of the apps.

@shankari great ! Unfortunately we have updated our app 2 weeks ago and do not plan the next update until a few weeks ahead. But we will test the status screen again as soon as we can.

**Comment by asiripanich** [comment]
> @asiripanich can you elaborate more on the scrolling issue? Some context may help me find the related issue.

I remember now that it was something I discussed with @atton16.

![RPReplay_Final1646008458](https://user-images.githubusercontent.com/17020181/156111093-153a47b6-d12d-43ed-9583-86dae2be072e.gif)

**Comment by shankari** [comment]
@asiripanich Is this on android or iOS?

**Comment by asiripanich** [comment]
iOS.

**Comment by shankari** [comment]
Alas, I don't have access to an iOS 14.3. The oldest simulator in my xcode is 14.3, and my test phones are all 12.x
But in the iOS 14.3 simulator, I don't see the scrolling issue.
Do you see this in the simulator as well? If so, it is easier to debug...

<img width="330" alt="Screen Shot 2022-03-01 at 9 42 30 AM" src="https://user-images.githubusercontent.com/2423263/156220607-8a36587a-2071-47ed-9d30-97cd923f97ab.png">

**Comment by asiripanich** [comment]
I think it was the latter. However, I'm quite familiar with the app so I know that you need to scroll up and down a few times before it let you scroll to the end. Not sure if an average user would know how to resolve this.

**Comment by shankari** [comment]
Let me know if you can reproduce in the simulator.

It is primarily a question of prioritization - is getting the scrolling right more important than dealing with https://github.com/e-mission/e-mission-docs/issues/704, or https://github.com/e-mission/e-mission-docs/issues/698?
