### ISSUE TITLE
Finish unifying diary and label screens

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#902]

**Comment by shankari** [comment]
- label details should be similar to diary details
- we can remove incident reporting during the migration although I want to add it back, potentially re-designed/better designed after the migration

**Comment by shankari** [comment]
Once you do the basic, I am happy to talk through performance/scalability with date choosing.

What should we do if a user picks a date from a year ago? How do they add more trips "to the bottom"?
When we do drop trips from the local cache?

**Comment by shankari** [comment]
two potential considations for the inferred mode display are:
- you could display the inferred mode in the labels instead of in separate icons so that when it got overridden, the inferred values would go away. Worthwhile to have detail which shows all the stages - inferred from sensor; inferred from prior trips; user input for explainability?
- maybe we should have text labels instead of icons for the inferred mode even if we keep them separate. When we first crated the diary screen, we used a random forest model for mode inference so we would only infer one of 5 modes so labels made sense. Then I implemented a GIS integration so we can essentially get any mode that is supported by open street map, which includes TRAM, LIGHT_RAIL, SUBWAY, FERRY (there's an open issue asking about FERRY)

**Comment by JGreenlee** [comment]
I have made significant progress on https://github.com/e-mission/e-mission-phone/pull/974.

@shankari I'm happy to discuss design for the ideas above: inferred modes in labels, text labels instead of icons, date choosing behavior -- but I wanted to get a working draft done first. So see what you think. I think the only major feature that is still missing from the label screen is draft trips

**Comment by JGreenlee** [comment]
Should draft trips appear in "To Label"?

As I have it currently, they appear in "Unlabeled" and "All Trips", but they don't have an `expectation` so they aren't appearing in "To Label".

**Comment by shankari** [comment]
Yes, as long as "To Label" is the default selection, they should appear in "To Label". I think you can fill in an expectation with no predictions and `to_label = true`. LMK if you need help with the structure of expected trips.
