### ISSUE TITLE
💄 Minor cleanup of rewrite

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#923]
While deploying the code in 
https://github.com/e-mission/e-mission-phone/pull/974
https://github.com/e-mission/e-mission-phone/pull/980
https://github.com/e-mission/e-mission-phone/pull/990

There are several minor fit and finish issues. If feasible, we should fix them, test and maybe even push to production before moving on

| Missing translation | Incorrect formatting | Map tiles not loading | Incorrect formatting (android only) |
|--------|----------|--------|-------|
| ![simulator_screenshot_03FB26D9-6B0C-418B-BB93-C20E096B8781](https://github.com/e-mission/e-mission-docs/assets/2423263/08df3554-fcc5-4edb-89ab-23e56c149914) | ![simulator_screenshot_26C710B4-3ABC-41F8-9C14-D938B6B40E83](https://github.com/e-mission/e-mission-docs/assets/2423263/7c896d8d-778f-4dc3-b591-8c81f73f5f0b) | ![simulator_screenshot_4488BDFD-46DE-40E3-94F1-424ADC96B6E4](https://github.com/e-mission/e-mission-docs/assets/2423263/294c4e82-6ce3-4cc0-a1dc-0a524f991700) | <img width="901" alt="Screenshot 2023-06-22 at 5 27 02 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/e69cd334-c2ec-41be-af30-f6cffbab1942"> |

**Comment by shankari** [comment]
The map tiles are not loading because of 

```
Some resources are blocked because their origin is not listed in your site's Content Security Policy (CSP). Your site's CSP is allowlist-based, so resources must be listed in the allowlist in order to be accessed.
A site's Content Security Policy is set either as via an HTTP header (recommended), or via a meta HTML tag.
To fix this issue do one of the following:
(Recommended) If you're using an allowlist for 'script-src', consider switching from an allowlist CSP to a strict CSP, because strict CSPs are more robust against XSS . See how to set a strict CSP .
Or carefully check that all of the blocked resources are trustworthy; if they are, include their sources in the CSP of your site. ⚠️Never add a source you don't trust to your site's CSP. If you don't trust the source, consider hosting resources on your own site instead.
```

Resource | Status | Directive | Source Location
-- | -- | -- | --
https://tile.openstreetmap.org/15/5271/12709.png | blocked | img-src | index.html#!/root/main/inf_scroll:0
https://tile.openstreetmap.org/15/5272/12709.png | blocked | img-src | index.html#!/root/main/inf_scroll:0
https://tile.openstreetmap.org/15/5271/12708.png | blocked | img-src | index.html#!/root/main/inf_scroll:0
https://tile.openstreetmap.org/15/5272/12708.png | blocked | img-src | index.html#!/root/main/inf_scroll:0

**Comment by shankari** [comment]
@JGreenlee

I am tempted to push this to staging so that we can come up with the full list of issues and fix all of them before going on to the more complicated parts of the rewrite

**Comment by JGreenlee** [comment]
> @JGreenlee
> 
> I am tempted to push this to staging so that we can come up with the full list of issues and fix all of them before going on to the more complicated parts of the rewrite

I am ok with pushing it to staging now so we can track more issues sooner. By now, #990 is fairly old and I'm already pretty far ahead of it. I think many of the issues we will see, I have already fixed in the process of rewriting -- but it would be good to get a complete list.

I expect to have the bulk of the label screen conversion wrapped up tomorrow or this weekend, and maybe that can be in our next staging release.

**Comment by shankari** [comment]
| Onboarding survey on android | Mode spacing is all messed up |
|-------|--------|
| <img width="405" alt="Screenshot 2023-06-23 at 4 47 01 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/d9c8144a-d207-4a7a-a17d-082c9d95ae52"> |  <img width="405" alt="Screenshot 2023-06-23 at 5 32 49 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/10d16224-2191-4f40-a18e-b9fa06167787"> |

**Comment by JGreenlee** [comment]
The above issues will be addressed, if not already addressed, in https://github.com/e-mission/e-mission-phone/pull/993 for the next staging release

### TODO:

Map tiles not loading - This only affects builds and not the devapp. The fix might be as simple as updating `<meta>` tags in `index.html` which sets Content Security Policy. I noticed a whitelist currently includes `nominatim.openstreetmap.org`, but not `tile.openstreetmap.org`

Sections / percents indicator - Actually, I still need to implement this indicator altogether on https://github.com/e-mission/e-mission-phone/pull/993. I was waiting for https://github.com/e-mission/e-mission-server/pull/917, which is now merged, so I should now be able to test against the complete implementation.
--I do know what caused this issue (I used the CSS `translate`, a shorthand for `transform: translate()`, which is a standard CSS property now but not supported in old versions of Android's Webview. I'll avoid it in case anyone hasn't updated their phone in a couple years)

### Try to reproduce later:

Demographics survey formatting - I was unable to reproduce this on the branch of https://github.com/e-mission/e-mission-phone/pull/993. I likely fixed it inadvertently, but we should double check on real devices on the next staging version

### Resolved:

Missing 'welcome' translation - just fixed in https://github.com/e-mission/e-mission-phone/pull/993

QRCode formatting - previously fixed in https://github.com/e-mission/e-mission-phone/pull/993

Datepicker formatting - fixed inadvertently in https://github.com/e-mission/e-mission-phone/pull/993 when I migrated it to React.
--The cause was definitely the aforementioned CSS `translate` shorthand

**Comment by shankari** [comment]
I'm still seeing the following issues:

| Formatting of save token screen on android | Label screen formatting seems to be fine although it is still not 100% clear from the color and icon that this is a bus (although the bus was detected correctly!) |
|------|-----|
<img width="397" alt="Screenshot 2023-06-29 at 9 59 19 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/57d574fe-ae7e-42f0-8149-ced643fe5799"> | <img width="397" alt="Screenshot 2023-06-29 at 10 00 14 AM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/12c6bfcd-dd3a-4d33-af09-b9d411c765a1"> |

**Comment by shankari** [comment]
I'm going to push this out now and submit my changes to the build when I return

**Comment by Abby-Wheelis** [comment]
I just updated my app and the profile page is broken on both test phones (ios and android). All strings are in the format `{{'control.edit-demographics'}}` and none of the buttons work. The screen is also not scrollable on either phone.

The label and dashboard screens look and behave fine, the profile screen is the only one having those issues. You can sort of see this picture, I don't have email set up on a test phone so I could not get a proper screenshot up
<img src="https://github.com/e-mission/e-mission-docs/assets/54848919/e05c49ac-f3aa-43db-9247-8c4277109a4d" width="200" />

**Comment by JGreenlee** [comment]
I can look at this myself, but do you want to try @Abby-Wheelis? It may be good to learn how to debug a physical device

**Comment by shankari** [comment]
I can verify this. @JGreenlee if you can get this fixed by EOD today, I can push out another release with this fix and with the changes in https://github.com/e-mission/e-mission-phone/pull/998

**Comment by shankari** [comment]
Error:

```
bundle.js:2 Error: [$injector:unpr] Unknown provider: eProvider <- e <- ControlCollectionHelper
http://errors.angularjs.org/1.6.7/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20ControlCollectionHelper
    at bundle.js:2:128028
    at bundle.js:2:151020
    at Object.s [as get] (bundle.js:2:152598)
    at bundle.js:2:151107
    at s (bundle.js:2:152598)
    at l (bundle.js:2:152903)
    at Object.invoke (bundle.js:2:152991)
    at Object.$get (bundle.js:2:151644)
    at Object.invoke (bundle.js:2:153237)
    at bundle.js:2:151127
```

**Comment by shankari** [comment]
So this may actually be related to the native build when the plugin-specific js files are not copied over.
Note that, by default, the settings files (`collect-settings.js` and `sync-settings.js`) are not in the e-mission-phone repo.
They are installed as part of the plugin install.

I hacked `index.js` to refer to these files

```
diff --git a/www/index.js b/www/index.js
index c2b2bb97..c7b6ae49 100644
--- a/www/index.js
+++ b/www/index.js
@@ -53,8 +53,10 @@ import './js/metrics.js';
 import './js/control/general-settings.js';
 import './js/control/emailService.js';
 import './js/control/uploadService.js';
-import './js/control/collect-settings.js';
-import './js/control/sync-settings.js';
+import '../platforms/android/platform_www/js/control/collect-settings.js';
+import '../platforms/ios/platform_www/js/control/collect-settings.js';
+import '../platforms/android/platform_www/js/control/sync-settings.js';
+import '../platforms/ios/platform_www/js/control/sync-settings.js';
 import './js/metrics-factory.js';
 import './js/metrics-mappings.js';
 import './js/plugin/logger.js';
```

But I bet that the change to optimize the webpack with hardcoded directories broke it.
Let's try copying it manually and see if that fixes it.

**Comment by JGreenlee** [comment]
@shankari I bet `collect-settings.js` and `sync-settings.js` didn't get the babel-plugin-angularjs-annotate treatment

**Comment by JGreenlee** [comment]
Yeah they are using the implicit annotations. That would cause it.
And explains why it only affects the Profile tab

**Comment by shankari** [comment]
Confirmed that it is *not* just the file paths. I ran `./bin/download_settings_controls.js` manually and then built, and I'm getting the same error.

**Comment by JGreenlee** [comment]
@shankari After copying, did you build webpack again or just cordova?

**Comment by shankari** [comment]
webpack too

```
$ history
./bin/download_settings_controls.js
npm run build
npx cordova emulate android
```

**Comment by JGreenlee** [comment]
@shankari And when you did that, you removed the hack from index.js right?

**Comment by JGreenlee** [comment]
I am fairly certain that this error results from `collect-settings.js` and `sync-settings.js` not getting 'fixed' by the babel plugin

But if they were copied over, as long as they were in the `www/` directory they should have been annotated the second time

**Comment by shankari** [comment]
Fixed:
<img width="220" alt="Screenshot 2023-06-29 at 2 07 01 PM" src="https://github.com/e-mission/e-mission-docs/assets/2423263/6f52167b-aaeb-4f93-b907-3bd7172143a5">

I copied the files over, but didn't revert the index.js change to include the non-platform locations.
After changing that as well, everything worked.

**Comment by JGreenlee** [comment]
Whew!

So, sounds like for the build configuration, we just need `download_settings_controls.js` to be run before webpack is run.
Should I add that at the front of the npm `build` script?

**Comment by shankari** [comment]
I can add it, I already have a change for the android release build pending...

**Comment by JGreenlee** [comment]
### TODO
Here's what I've noticed:
- the most recent trip is always left off. You have to "Show More Travel" to see it or any draft trips
- "Show Older Travel" and "Show More Travel" are not internationalized
- when you load more trips, their address names don't fill in
- activities don't show up until after a refresh
- some 'mode' icons (I noticed 'car' and 'bike') are showing up cropped / too big for their bounding box

**Comment by shankari** [comment]
> the most recent trip is always left off. You have to "Show More Travel" to see it or any draft trips

Following up on this, the last trip is also displayed incorrectly (on my phone). My last trip was from Palo Alto to home, but the map in the list view shows a walk around Palo Alto. The detail screen shows the correct trip though (see screenshots).
Also, the map in the list view seems to be zoomable. I'm not sure if that is a good or a bad idea. Is it confusing/does it happen that we try to scroll but the map zooms instead.
And also, the place names are not showing up.

| List view (wrong) | Detail view (right) | Zoomed list view (???) |
|------|------|------|
| ![Screenshot_20230629-152356](https://github.com/e-mission/e-mission-docs/assets/2423263/d3fcec1b-a1a0-4304-859b-fb19441b4abe) | ![Screenshot_20230629-152424](https://github.com/e-mission/e-mission-docs/assets/2423263/b54fc641-ab1f-458c-9909-4c0993ff0a81) | ![Screenshot_20230629-152503](https://github.com/e-mission/e-mission-docs/assets/2423263/01dc6b3d-8667-43d7-bca9-02cf0a3e3da2) |

**Comment by shankari** [comment]
Comments from @mRaffill
- Don't have walk and car be shades of red since they look similar, could be hard for people with red/green blindness
- Really like how the modes are showing up; that is most helpful part of the diary; not too big and not too hidden either - that's great
- looks a lot more professional now
- Don't like how "Add trip details" and "Add Activity" are are slightly offset - looks like you tried to make them aligned but did something wrong with the spacing and it didn't work
- In the time-use survey, the check boxes just highlight the outline of the box, don't actually add a check mark so I couldn't tell that I had selected it
- "show more travel" or "show older travel" is good; much better than the weird download button before (@shankari's UI design skills... shakes head and laughs)
- I really like that you can see the drafts without going into a separate diary
- "This looks so good actually" Such a big step up from the previous UI
- No boundary saying when your first trip was; I could go back to 2020 in the calendar and then it just hung and the dates were showing up as 2023/06/29 to 2023/06/29
- If you do later (e.g. December) just shows draft trips and "show older travel". Dates are still showing as 2023/06/29 to 2023/06/29
- once I set a valid date, it worked again and it makes sense

**Comment by JGreenlee** [comment]
> * No boundary saying when your first trip was; I could go back to 2020 in the calendar and then it just hung and the dates were showing up as 2023/06/29 to 2023/06/29
> * If you do later (e.g. December) just shows draft trips and "show older travel". Dates are still showing as 2023/06/29 to 2023/06/29

Yeah... that's another reason we will need to use `react-native-paper-dates` sooner or later.

https://caniuse.com/?search=input%20date

As much as I love how the native iOS datepicker looks, it doesn't offer any way to constrain inputs. If I put `min` and `max` attributes, it would work great on Android (days outside the range would be disabled), but iOS would just ignore it.

**Comment by shankari** [comment]
Closing this since https://github.com/e-mission/e-mission-phone/pull/1000 is merged
Next round of cleanup will be tracked in #932
